# Generated by Django 5.1.2 on 2024-12-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
